checker.go

This patch ensures that repeated fields only use the repeated rule, and this is enforced at build time by the checker. Previously, the checker would fail to catch a repeated field with a scalar rule applied and output erroneous code.

Checker: fail build on singular rules used on repeated fields

---

templates/cc/enum.go
templates/cc/register.go
tests/harness/cc/harness.cc

Translate the remaining code required to make C++ enum validation work.

Implement C++ validation for enums

---

templates/cc/bytes.go
templates/cc/msg.go
templates/cc/register.go
tests/harness/cc/harness.cc

Anything involving pattern matching is marked as unimplemented; everything else is done.

Translate most of the byte array validation code to C++

---

templates/cc/duration.go
templates/cc/register.go
tests/harness/cases/wkt_duration.proto
tests/harness/cc/harness.cc
validate/validate.h

This should be capable of handling arbitrary Durations, once #34 is resolved for checker.go.

templates: C++ Duration support.

---

templates/cc/register.go

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

templates: add "inline" C++ keyword.

---

tests/harness/executor/executor.go

Use all available cores by default, allow for overriding from the
command line.

Add flag to control test parallelism

---

validate/validate.h

and use type_index instead of hash_code for associative containers.
tested locally with latest envoy master.
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

fix static initialization fiasco

---

bazel/pgv_proto_library.bzl
bazel/protobuf.bzl

Run buildifier from https://github.com/bazelbuild/buildtools on the Starlark code.

Apply standard formatting to .bzl files.

---

java/pgv-java-validation/src/main/java/com/lyft/pgv/validation/JavaHarness.java
validate/validate.proto

Fixes #65. Only affects Java. #54

Add java_package option to validate.proto

---

templates/cc/enum.go
templates/cc/register.go
templates/cc/repeated.go
tests/harness/cases/enums.proto
tests/harness/executor/cases.go

Fixes #139 
This patch addresses an issue when validating enums in a repeated fields.

C++: Properly handle repeated enums

---

WORKSPACE
bazel/pgv_proto_library.bzl
bazel/protobuf.bzl

`sed "s#lyft_protoc_gen_validate#envoyproxy_protoc_gen_validate#g"`

Fix Bazel workspace name

---

WORKSPACE

Fixes #182
Signed-off-by: Ryan Michela <rmichela@salesforce.com>

Fix bazel 0.25.0

---

README.md

Fix Maven groupId in readme

---

java/pgv-java-grpc/src/test/java/io/envoyproxy/pgv/grpc/ValidatingClientInterceptorTest.java
java/pgv-java-grpc/src/test/java/io/envoyproxy/pgv/grpc/ValidatingServerInterceptorTest.java
java/pgv-java-grpc/src/test/proto/GooDBYe.proto
java/pgv-java-grpc/src/test/proto/hello.proto
templates/java/register.go

Correctly handle proto files and messages with consecutive upper-case

---

.circleci/config.yml
java/RELEASING.md

A small tweak to the release instructions found as part of #168.

Update java release instructions

---

README.md

Fix documentation deficiencies noted in #168 and #185.

Java usage

---

validate/validate.pb.go
validate/validate.proto

Switch extension numbers to registered value

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/StringValidation.java
java/pgv-java-stub/src/test/java/io/envoyproxy/pgv/StringValidationTest.java

* Changed Java string length validation to work for UTF-8.

Changed Java string length validation

---

module/validate.go

This was one of the two things breaking envoy from upgrading to PGV. The second is within envoy itself, and I will file that PR after this one is merged.

only add a generater java file if lang == "java"

---

.github/stale.yml

Stalebot configuration

---

tests/harness/python/harness.py
validate/validator.py

Update Python interface so that validate function can be cached.

Update Python Interface

---

Dockerfile
Makefile
templates/cc/bytes.go
templates/cc/enum.go
templates/cc/map.go
templates/cc/register.go
templates/cc/string.go
templates/cc/timestamp.go
templates/shared/context.go
tests/harness/cases/maps.proto
tests/harness/cc/harness.cc
tests/harness/executor/cases.go
validate/validate.h
validate/validator.py

Additionally, provides details for unimplemented validation
features and adds some generated, but not executed, test
cases for C++. Fixes some small errors in the Docker- and
Makefiles.
Fixes: #130
Signed-off-by: Stephan Zuercher <zuercher@gmail.com>

c++: recursively validate values in map fields

---

validate/validator.py

I recently started to use this extension and realized validating deeply nested messages takes a very long time because it generates a function every time. I modified the code so the generated func can be retrieved from cache.

Cache generated func

---

templates/goshared/timestamp.go
tests/harness/cases/wkt_timestamp.proto
tests/harness/executor/cases.go
validate/validator.py

Fixed timestamp comparison used when  "less/greater than now" constraints are combined with a "within" constraint on timestamps and added test-cases for these scenarios.

fix timestamp comparison for greater than now & within

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/StringValidation.java
tests/harness/executor/cases.go

Fix email validation for empty strings

---

templates/go/file.go
templates/shared/functions.go
templates/shared/well_known.go

Fixes https://github.com/envoyproxy/protoc-gen-validate/issues/419
Signed-off-by: John Howard <howardjohn@google.com>

Conditionally add regex for UUID only when needed

---

README.md

Just fixing one small syntax error on a validator snippet

Fix snippet syntax on README

---

README.md

Update README.md to use inclusive language as per the main repo.

readme: use inclusive language

---

validate/validate.h

undef conflicting symbols on Windows

---

templates/goshared/register.go
tests/harness/cases/enums.proto

Signed-off-by: Matt Klein <mklein@lyft.com>

go: more regression fixes for optional values

---

java/sonatype_nexus_upload.py

Signed-off-by: Alan Chiu <awlchiu@gmail.com>

Add artifact id as parameter for uploading pom

---

.github/workflows/maven-deploy.yaml

Signed-off-by: Elliot Jackson <13633636+ElliotMJackson@users.noreply.github.com>

Create maven deploy CI

---

.github/workflows/maven-deploy.yaml
java/settings.xml

Provides settings & secrets necessary to publish github packages  
Signed-off-by: Elliot Jackson <13633636+ElliotMJackson@users.noreply.github.com>

Update maven-deploy secrets

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/Buf.java

Signed-off-by: Alan Chiu <awlchiu@gmail.com>

Add Buf class for maven override verification

---

.github/dependabot.yml

Includes coverage for gomod in `root` & `tests` as well as maven in `java`

TCN-612 Configure Dependabot

---

.github/workflows/version-bump.yaml

This reduces our security risk

Pin Token Exchange Version

---

Dockerfile
bazel/dependency_imports.bzl

Upgrade go to 1.19.7

---

README.md

I followed the advice from [this comment](https://github.com/bufbuild/plugins/issues/202#issuecomment-1337579775) to get this to work with the Buf command. 
It took me a while to figure out, so I think this information belongs in the readme.

Add example of using PGV with Buf CLI

---

README.md

Update README.md to incl blog post

---

.golangci.yml
templates/java/BUILD.bazel
templates/java/unimplemented.go

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

Enable unused linter

---

.goreleaser.yaml

Fixes: [1064](https://github.com/bufbuild/protoc-gen-validate/issues/1064)

Use CGO_ENABLED=0 for all compilations

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/RequiredValidation.java

Fixes https://github.com/bufbuild/protoc-gen-validate/issues/1141

Use Message instead of GeneratedMessageV3

---

python/requirements.in
python/setup.cfg
tests/harness/python/requirements_test.py

Require astunparse for older python versions

---

bazel/protobuf.bzl

See https://github.com/bazelbuild/bazel/issues/17032
Caught by https://github.com/bazelbuild/bazel-central-registry/pull/4402#issuecomment-2826810034

Fix incompatibility with --incompatible_disable_starlark_host_transitions
