tests/harness/BUILD
tests/harness/cases/BUILD
tests/harness/executor/BUILD
tests/harness/executor/executor.go

Fix the bazel build files so that `bazel build :protoc-gen-validate` builds a binary and `bazel test //tests/...` runs all the included test cases (which currently fail).

Fix bazel build

---

WORKSPACE
bazel/pgv_proto_library.bzl
tests/harness/BUILD
validate/BUILD

This allows other Bazel consuming protos to be able to import
validate.proto in a language neutral way, needed by data-plane-api.
Also s/protobuf_bzl/com_google_protobuf/ to conform to standard
repository naming across Bazel projects.

bazel: export //validate proto_library target.

---

Makefile
bazel/go_proto_library.bzl
tests/harness/cases/BUILD
tests/harness/executor/BUILD
tests/harness/go/harness.go

The bazel-built test executable was executing but not succeeding because the
validation code was not getting linked in at compile-time and the test used
lazy duck-typing to validate. This patch
1. makes the test fail loudly if an input doesn't implement the correct
interface
2. updates the bazel rule to link in the validation code
3. fixes the test code so it imports the validation code
4. modifies the CI script to also run the tests via bazel

bazel: link validation libraries into test executable

---

WORKSPACE
validate/BUILD

Needed to support Python protodoc tool in data-plane-api.

bazel: Python support for validate.proto.

---

.gitignore
Makefile
checker.go
module.go
validate/validate.proto

This patch addresses an issue, noticed in https://github.com/envoyproxy/data-plane-api/pull/267#discussion_r153074469, where WKT wrappers were not properly detected and verified by the checker.
Also, turning on linters in CI against the Go code as my IDE caught a couple of gofmt/vet issues.

Checker: more robust WKT wrapper detection

---

templates/cc/register.go
tests/harness/cc/harness.cc

Instead of holding off on translating the validation code for a field type until all the cross-language issues are worked out (#22), support exceptions as a means of conveying to the calling code that a validation type is not yet implemented. This will allow the C++ validation code to move forward one constraint at a time instead of one field type at a time.

Allow partially implemented C++ validation code

---

bazel/pgv_proto_library.bzl

Need to use workspace qualified names to support pgv_proto_library use
across repos.

bazel: fix cross repo regression in pgv_proto_library.

---

Makefile
templates/cc/repeated.go
templates/go/repeated.go
templates/shared/context.go
tests/harness/cases/repeated.proto
tests/harness/executor/BUILD
tests/harness/executor/cases.go
tests/harness/executor/executor.go
tests/harness/executor/harness.go
tests/harness/executor/worker.go

This patch addresses an issue (in both Go and C++) where messages embedded in a repeated field would not be validated unless the repeated field itself had validation rules applied. Additionally, the `skip` rule on messages embedded in repeated fields caused compilation errors due to unused variables for the elements. The current solution here still leaves the loop (which hopefully gets optimized out by the compiler); a later fix should ensure the loop is not emitted.
Finally, some cleanup to some of the bazel rules to properly run the test harness. Later on, may convert the harness to utilize the Go test framework for better portability (and limiting which test cases are executed).

Validate message elements in repeated fields

---

templates/cc/message.go
templates/cc/msg.go

These got missed in PR #44. This changes the signature of the validation
functions. This shouldn't affect calling code since pgv::ValidationMsg is an alias for
std::string.

Use pgv::ValidationMsg as C++ Validate() error arg

---

tests/harness/executor/cases.go

The package names don't match the import paths so it's hard to tell
where `cases` and `other_package` are actually defined.

Use named imports for Go protobuf imports

---

WORKSPACE

The native git_repository rule does not honor git's proxy settings
(https://github.com/bazelbuild/bazel/issues/3893), so this means
that anything that depend on protoc-gen-validate will fail when building
while behind a proxy.
Example of failing build of envoy:
```
DEBUG: /root/.cache/bazel/_bazel_root/2ca1f4ebdc59348ffdc31d97a51a98d5/external/envoy/bazel/repositories.bzl:84:5: External dep build exited with return code: 0
ERROR: /root/.cache/bazel/_bazel_root/2ca1f4ebdc59348ffdc31d97a51a98d5/external/com_lyft_protoc_gen_validate/validate/BUILD:35:1: no such package '@com_github_golang_protobuf//proto': failed to fetch com_github_golang_protobuf: # cd .; git clone https://github.com/golang/protobuf /root/.cache/bazel/_bazel_root/2ca1f4ebdc59348ffdc31d97a51a98d5/external/com_github_golang_p …
```

Use Skylark git_repository workspace rule

---

BUILD
WORKSPACE
tests/harness/go/BUILD

This updates the version of rules_go to [0.9.0](https://github.com/bazelbuild/rules_go/releases/tag/0.9.0). The BUILD files changes were
necessary to work around a linking error that happens under 0.9.0.
The fix was based on https://github.com/bazelbuild/buildtools/issues/201, but I don't really know much about the go build chain, so I don't really know what's happening, nor do I know if there's any specific motivation behind structuring the BUILD file the way it was. I'd be happy to file a bug against rules_go if this change seems like it should unnecessary, but I figured I'd put this up in case we're okay with the workaround. 
This update also adds these deprecation warnings:
```
DEBUG: /private/var/tmp/_bazel_snowp/3bae0aee9d5211471587d3b4956c9db7/external/io_bazel_rules_go/go/private/r …
```

Update rules_go to 0.9.0

---

tests/harness/cases/strings.proto
tests/harness/executor/cases.go

Per #68, there might be some weirdness with escapes in regex. This patch adds tests to simulate the issue, which seems to behave as expected. Will likely also add to the docs with this patch to clarify the need to escape the pattern string since protoc does not treat it as literal.
Closes #68

Add tests for escape sequences in regex patterns

---

README.md
templates/cc/duration.go
tests/harness/cases/wkt_duration.proto
tests/harness/cc/harness.cc
tests/harness/executor/cases.go

Previously, if the duration field was missing, it would short circuit
evaluation of following fields in the message the template was embedded
in. This triggered the server config proto fuzz tests for Envoy.

templates: fix Duration C++ code generation bug.

---

README.md

The extra -I are needed to have the
import "validate/validate.proto";
work -- and it needs to be imported like this because that's how the
filedescriptor is registered, see
https://github.com/lyft/protoc-gen-validate/blob/e60e7f91da4/validate/validate.pb.go#L3049
Also the proto file needs package, otherwise, you'll see
protoc-gen-go: error:can't find object with type ..Person
And those character classes in the regex don't seem to be supported?
Using them, I ended up seeing
example.proto:11:39: Invalid escape sequence in string literal.
example.proto:11:41: Invalid escape sequence in string literal.
example.proto:11:49: Invalid escape sequence in string literal.
example.proto:11:51: Invalid escape sequence in string literal.
This should fix #56.
I'm well aware that I'm not telling you …

README: fix example.proto and protoc includes

---

bazel/pgv_proto_library.bzl
bazel/protobuf.bzl
tests/harness/BUILD
tests/harness/cases/BUILD
tests/harness/cases/other_package/BUILD
tests/kitchensink/BUILD
validate/BUILD

This replaces the use of cc_proto_library / proto_gen from the
@com_google_protobuf//:protobuf.bzl. The reason for doing so is that
newer versions of google/protobuf have changed cc_proto_library +
proto_gen so that they no longer work with pgv_cc_proto_library.
pgv_proto_library now takes a proto_library containing the protos
instead of a list of proto files. The approach for generating the protoc
command line arguments was taken from bazelbuild/rules_go
The py_proto_library imported from @com_google_protobuf//:protobuf.bzl
is used by Envoy, so we left it in.
Note: when integrating this commit with Envoy, we see the error:
```
2018/08/07 11:17:51 protoc-gen-go: error:[gatherer][file:envoy/config/trace/v2/trace.proto]proto package names should not be mixed in the same directory …
```

Break dependency on protobuf.bzl from google/protobuf for C++

---

validate/validate.h

This fixes my local build, which otherwise complains about a non-templated type "function" in namespace `std`.

Add missing #include for std::function

---

Makefile
templates/cc/enum.go
templates/cc/register.go
templates/go/file.go
templates/gogo/file.go
templates/goshared/register.go
tests/harness/cases/enums.proto
tests/harness/cases/other_package/embed.proto
tests/harness/executor/cases.go

This patch addresses an issue around the `defined_only` rule for enums when imported from a different package. In Go (and gogo), the external package must be imported to access the defined list of values for that enum; while in C++, the IsValid function should be prefixed with the fully-qualified namespace.

enums: properly handle enums imported from an external package/namespace

---

templates/cc/register.go
tests/harness/cases/enums.proto
tests/harness/cases/other_package/embed.proto
tests/harness/executor/cases.go

This patch addresses a bug introduced in #110 which neglected to prefix `*_IsValid` functions with the parent message names for nested enums.

enum: properly prefix validation function name

---

Dockerfile
WORKSPACE

This includes fixes for a change to the Starlark API around how compiler
toolchains are detected and accessed.

Bump Bazel go rules

---

java/pgv-java-stub/src/main/java/com/lyft/pgv/ExplicitValidatorIndex.java
java/pgv-java-stub/src/main/java/com/lyft/pgv/ReflectiveValidatorIndex.java

As requested, I've added `ExplicitValidatorIndex.java` as part of #54, but I'm not sure it's needed.
Generated validators for message type fields continue to use `ReflectiveValidatorIndex`, which sort of defeats the purpose of this class. I don't see an easy way to allow users to swap out which index the generated validators use, without introducing more static global variables.
Perhaps we can postpone this class until it's requested?

Implement java ExplicitValidatorIndex

---

templates/cc/register.go
templates/pkg.go

Decouples from the Go output path overrides.
Fixes #41.

cc: use raw path generation for C++ validation files.

---

templates/cc/map.go
tests/harness/cc/harness.cc

Implements min/max pair validations in C++ and adds the map test cases to the test harness.
Progress on #130.

Implement map.min/max keys in C++

---

bazel/pgv_proto_library.bzl

When using the rule (macro) from another workspace it tries to load the dependencies from there.
This forces Bazel to look into @com_lyft_protoc_gen_validate for the relevant targets.
I am not sure the problem also exists for go and cc since I don't use these, if desirable I can add the deps there as well

Prefix java pgv rule dependencies with workspace name

---

templates/java/register.go

When creating a constraint like this:
repeated SomeEnum enums = 1 [ validate.rules).repeated .items.enum = { not_in: [ 0 ] } ];
The resulting array in Java that holds the not_in values is typed like:
private final Object[] SOME_ENUM__NOT_IN = Object[]{
Object.forNumber(0),
}; 
It should be:
private final SomeEnum[] SOME_ENUM__NOT_IN = SomeEnum[]{
SomeEnum.forNumber(0),
}; 
After some digging the error turned out to that within a repeated, the fqn for an enum wasn't getting properly resolved.

Java: set correct classname for repeated enum (not)in constraint

---

WORKSPACE

Since Bazel 0.22.0, new_http_archive is deprecated and its usage results
in error.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

bazel: Stop using new_http_archive function

---

WORKSPACE

The current bazel version complains about use of cfg="data" on an attribute in the old version of bazel-gazelle. The current release doesn't have this problem.

Update bazel-gazelle version

---

templates/cc/register.go

The packageName function now returns a fully-qualified prefix. When generating C++ names, full namespace qualification will avoid ambiguity in namespace resolution.

Update register.go to fully qualify namespaces

---

.circleci/config.yml

I was watching the PR and saw that the build broke (https://circleci.com/gh/envoyproxy/protoc-gen-validate/95) thought I could donate the fix!
@rmichela 
@rodaine 
The working directory of the script is the java directory which is why the .circleci directory is not found in the current directory where the build is triggered

Fix the circle ci build script to point to the settings file

---

WORKSPACE
bazel/protobuf.bzl

When building envoy with bazel@HEAD to test for regressions, bazel CI
tests with upcoming incompatible changes. This PR fixes a few of those
experienced upstream:
`--incompatible_require_ctx_in_configure_features` & `--incompatible_enable_cc_toolchain_resolution`:
Updated rules_go to include upstream fixes for these.
`--incompatible_depset_is_not_iterable`:
Call `to_list` where needed
`--incompatible_disable_deprecated_attr_params`:
Change `single_file` to `allow_single_file`
`--incompatible_no_support_tools_in_action_inputs`:
Move `ctx.executable._plugin` to `tools` instead of `inputs`
`--incompatible_disable_legacy_proto_provider`:
Update proto API usage following https://github.com/bazelbuild/bazel/issues/7152

Update for bazel incompatible changes

---

java/pgv-java-grpc/src/main/java/io/envoyproxy/pgv/grpc/ValidatingClientInterceptor.java
java/pgv-java-grpc/src/main/java/io/envoyproxy/pgv/grpc/ValidatingServerInterceptor.java
java/pgv-java-grpc/src/main/java/io/envoyproxy/pgv/grpc/ValidationExceptions.java

Added a small helper class to standardize the conversion of a `ValidationException` to gRPC's `Status.INVALID_ARGUMENT`.

Add Java ValidationExceptions helper

---

java/pgv-java-stub/pom.xml
java/pgv-java-stub/src/test/java/io/envoyproxy/pgv/ReflectiveValidatorIndexTest.java
java/pgv-java-stub/src/test/proto/embedded.proto
templates/java/file.go

Fixes #208
It appears validators for nested message types aren't being properly generated when `java_multiple_files=true`.

Embedded messages in protos with java_multiple_files=true throws NullPointerException

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/ReflectiveValidatorIndex.java
java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/StringValidation.java

* Changed `Charset.forName("UTF-8")` to `StandardCharsets.UTF_8` to avoid string construction and typos.
* Removed Google `CharMatcher` dependency by adding a faster pure Java utility function to validate if a string consists solely of ASCII characters or not. However, the new function like the previous one still allows for control characters.

Changed Java details

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/StringValidation.java
java/pgv-java-stub/src/test/java/io/envoyproxy/pgv/StringValidationTest.java

* Added support for quoted email addresses (as per RFC).
* Added guardian around display email address extraction to execute the logic only if we are certain that it is in display format.
* Changed logic to extract email address from display form. Replaced the regular expression with a simpler loop based algorithm.
* Changed the email validator instance retrieval. Placed it in a lazy holder class which means that we get the instance when it is first required and keep a reference on the object for the lifetime of the program so that subsequent retrievals are faster (which are likely since it was required). No additional object is allocated because we only keep a reference on the already existing instance.

Changed Java email validation

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/StringValidation.java
java/pgv-java-stub/src/test/java/io/envoyproxy/pgv/Assertions.java
java/pgv-java-stub/src/test/java/io/envoyproxy/pgv/StringValidationTest.java

* Changed Java UUID validation from a regular expression to a hardcoded finite state machine. This should provide a significant speed-up.
* Added UUID simple format support to Java UUID validation (the simple format is without dashes).

Changed Java UUID from Regex to FSM

---

validate/validate.h

On Windows we only include winsock2, not winsock
Signed-off-by: Yechiel Kalmenson <ykalmenson@pivotal.io>
Example of errors currently generated by using the winsock.h 1990's era legacy declarations;
ERROR: C:/_eb/external/envoy_api/envoy/config/filter/http/buffer/v2/BUILD:5:1: C++ compilation of rule '@envoy
_api//envoy/config/filter/http/buffer/v2:buffer_cc' failed (Exit 2)
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared\ws2def.h(103): warning C4005: 'AF_IPX': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winsock.h(457): note: see previous definition of 'AF_IPX'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared\ws2def.h(144): warning C4005: 'AF_MAX': macro redefinition
C:\Program Files (x86)\Windows …

Fix winsock include on windows

---

templates/go/file.go
templates/gogo/file.go
templates/goshared/BUILD.bazel
templates/goshared/known.go
templates/goshared/register.go

If a proto file has a name like `str-ing.proto`, the post processor would complain as Golang variables cannot have hyphens in their name. 
This change just converts the file name to snake case to avoid this problem.

Convert File Name to Snake Case for UUID Pattern matching variables

---

Makefile
tests/generation/multi_file_java_test/BUILD
tests/generation/multi_file_java_test/README.md
tests/generation/multi_file_java_test/main.cc
tests/generation/multi_file_java_test/test.proto

this adds in a regression test for the multiple_java_files option
trying to generate java files even when java wasn't an output.
this test breaks before the fix, but works on master since the
fix is in play.

regression test for multiple_java_files

---

validate/validate.h

<windows.h> uses macros to #define a ton of symbols, two of which (DELETE and GetMessage)
interfere with our code. DELETE shows up in the base.pb.h header generated from
api/envoy/api/core/base.proto. Since it's a generated header, we can't #undef DELETE at
the top of that header to avoid the collision. Similarly, GetMessage shows up in generated
protobuf code so we can't #undef the symbol there.
Signed-off-by: @wrowe

undef conflicting macros on windows

---

gogoproto/gogo.proto

The copy of [gogoproto](https://github.com/gogo/protobuf) is missing option `go_package`. This will cause generated code got wrong import path in Golang.
```go
import (
_ "gogoproto"
)
```
And the Go compiler will complain about cannot find the `gogoproto` package.
After fixing, the import path will look like this
```go
import (
_ "github.com/gogo/protobuf/gogoproto"
)
```
Then we're good to go.

Add missing go_package for gogoproto

---

WORKSPACE
bazel/dependency_imports.bzl
bazel/pip_dependencies.bzl
bazel/repositories.bzl
tests/harness/python/BUILD

Fix the Bazel build by updating protobuf to v3.9.1, then restructure the loading of external repositories to address #254.

Clean up Bazel build

---

validate/validate.h

We found a few more conflicting symbols on Windows (see https://github.com/envoyproxy/protoc-gen-validate/pull/247 for the last few we found).
Relevant [Slack discussion](https://envoyproxy.slack.com/archives/C78HA81DH/p1565360960105300)
Signed-off-by: @wrowe

undef conflicting symbols on windows

---

.gitignore
rule_comparison.md
templates/cc/msg.go
templates/cc/register.go
templates/cc/string.go
validate/validate.h

this commit implements utf-8 length string checking in C++ for
validations, and updates the readme table.
---
there's also a small update to the gitignore, to ignore a __pycache__
dir that was created for me when running make ci locally inside of
docker.
---
Note this does use a deprecated (in c++17) feature: `codecvt`. This was a tough choice but I thoroughly believe it's the best choice for this particular feature:
- According to the deprecation proposal it cannot be removed, until a replacement exists: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0618r0.html in which case we could switch to that when it comes out.
- Bringing in a library for a singular length function seems incredibly wasteful. Maybe if we were doing more utf-8 specific validation? However using one small …

implement utf-8 length for c++ validation

---

bazel/protobuf.bzl
templates/cc/BUILD.bazel
templates/cc/file.go
templates/cc/register.go
tests/harness/cases/BUILD
tests/harness/cases/filename-with-dash.proto
tests/harness/cc/harness.cc
tests/harness/python/harness.py

This patch converts the base file name into `screaming_snake_case` instead
of `upper` for cc macro generation.
This is motivated by:
```
INFO: From Compiling external/com_github_openzipkin_zipkinapi/zipkin-jsonv2.pb.validate.cc:
In file included from bazel-out/k8-opt/bin/external/com_github_openzipkin_zipkinapi/zipkin-jsonv2.pb.validate.cc:5:
bazel-out/k8-opt/bin/external/com_github_openzipkin_zipkinapi/zipkin-jsonv2.pb.validate.h:37:31: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
^
1 warning generated.
```
As reported in
https://github.com/envoyproxy/envoy/pull/6985#issuecomment-526658473.
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

cc: Convert base file name to screaming snake case

---

bazel/pgv_proto_library.bzl
bazel/protobuf.bzl

This PR updates proto providers to fix PGV build with Bazel 1.0. 
* Bazel 1.0 flipped a flag to disable legacy proto providers, so a rule needs to require a provider from `ProtoInfo` rather than from the provider `"proto"`. See:
https://github.com/bazelbuild/bazel/issues/7152
* Bazel 1.0 updates python so that `maxsplit` is a positional argument. See:
https://github.com/bazelbuild/bazel/issues/9998
Signed-off-by: Asra Ali <asraa@google.com>

build: build fix from bazel version 1.0 update 

---

validate/validate.h

The C++ not operator is not supported by all compilers.
Use ! instead.
Signed-off-by: Stephan Zuercher <zuercher@gmail.com>

validate: remove use of not operator

---

validate/validate.h

This patch prevents us from allocating temporary strings to count
the string's length in unicode code points, and drops the use of
the deprecated API codecvt introduced in
https://github.com/envoyproxy/protoc-gen-validate/pull/256
It is unclear how we wire this against protobuf's header file,
src/google/protobuf/stubs/strutil.h
so this patch is not ready for merging quite yet.
Resolves a win32 issue of missing char32_t-based codecvt
implementations in their stdlib (win32 favors uchar.)
Signed-off-by: Yechiel Kalmenson <ykalmenson@pivotal.io>
Signed-off-by: William A Rowe Jr <wrowe@pivotal.io>

Do not allocate/copy to a utf-32 string to count a utf-32 len.

---

Dockerfile
bazel/repositories.bzl

* maven_jar is deprecated. move to jvm_maven_import_external
* pip imports failing because python is missing
Signed-off-by: Asra Ali <asraa@google.com>

build: fix PGV build 

---

gogoproto/gogo.proto

The `gogo.proto` file in the root level of the project is missing some fields which our project is using.
This PR just updates the proto file to have said fields.

updated gogoproto

---

README.md

Ran into the same issue as https://github.com/envoyproxy/protoc-gen-validate/issues/271, so I figured I'd add it to the README.

added packages and input paths info to the README

---

bazel/repositories.bzl

Use of plaintext HTTP to Maven Central servers is not possible any longer
and mandates the use of HTTPS.
For more information, please refer to
https://blog.sonatype.com/central-repository-moving-to-https
Fixes envoyproxy/protoc-gen-validate#310

Update Maven Central server URLs to use HTTPS

---

templates/shared/well_known.go
tests/harness/cases/wkt_wrappers.proto
tests/harness/executor/cases.go

Fix missing `_validateUuid` method for this example of validation
```
google.protobuf.StringValue partner_id = 19 [
(validate.rules).string.uuid = true,
(validate.rules).message.required = false
];
```

Add _validateUuid method for optional string wrapper

---

java/pgv-java-grpc/pom.xml
java/pgv-java-grpc/src/main/java/io/envoyproxy/pgv/grpc/ValidatingClientInterceptor.java
java/pgv-java-grpc/src/main/java/io/envoyproxy/pgv/grpc/ValidatingServerInterceptor.java
java/pgv-java-grpc/src/main/java/io/envoyproxy/pgv/grpc/ValidationExceptions.java
java/pgv-java-grpc/src/test/java/io/envoyproxy/pgv/grpc/ValidatingClientInterceptorTest.java
java/pgv-java-grpc/src/test/java/io/envoyproxy/pgv/grpc/ValidatingServerInterceptorTest.java
java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/ValidationException.java
java/pom.xml

Hi,
A java implementation of https://github.com/envoyproxy/protoc-gen-validate/issues/48

proto field name to validation error #48 (Java)

---

Dockerfile

The existing 1.10 version does not support some library methods used by
the lint checker, so upgrade to 1.13.9.

Bump the version of Go used in the dockerfile

---

Makefile
bazel/pgv_proto_library.bzl
bazel/protobuf.bzl
bazel/repositories.bzl
java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/BUILD
java/pgv-java-validation/src/main/java/io/envoyproxy/pgv/BUILD
java/pgv-java-validation/src/main/java/io/envoyproxy/pgv/validation/BUILD
tests/generation/multi_file_java_test/BUILD
tests/harness/BUILD
tests/harness/cases/BUILD
tests/harness/cases/other_package/BUILD
tests/harness/cc/BUILD
tests/harness/java/BUILD
validate/BUILD

For https://github.com/envoyproxy/envoy/issues/9490 https://github.com/envoyproxy/envoy/issues/9489 https://github.com/envoyproxy/envoy/issues/9488
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

build: make it build with `bazelisk --strict`

---

templates/cc/in.go
templates/cc/msg.go
templates/goshared/msg.go
templates/goshared/register.go
tests/harness/cases/repeated.proto
tests/harness/executor/cases.go

Generate code for C++ and Go for repeated.items.enum.{in, not_in} validations, and add test cases.
Fixes #329

Fix support for repeated enums inclusion check

---

tests/harness/executor/executor.go
tests/harness/executor/harness.go
tests/harness/executor/worker.go

I am building PGV support for [ScalaPB](http://scalapb.github.io). As ScalaPB offers many ways for users to customize the generated code and the generator is written in Scala, it would be impractical to add ScalaPB support directly in here.
We have started to put some effort in https://github.com/scalapb/scalapb-validate and it would be nice to be able to run PGV's test harness against scalapb-validate. To accomplish that, I would like to be able to specify an external program to the harness.
See #322

Add support for external test harness

---

validate/validator.py

In Python 3.8:
```
/validate/validator.py:914: SyntaxWarning: "is not" with a literal. Did you mean "!="?
elif str(option_value.message) is not "":
```
https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/

Fix "SyntaxWarning: "is not" with a literal. Did you mean "!="?"

---

README.md

Checking against the definitions in https://github.com/envoyproxy/protoc-gen-validate/blob/master/validate/validate.proto#L767,
I believe this should say "const" here.

README.md: fix reference to timestamp.const rule

---

templates/goshared/register.go
tests/harness/cases/repeated.proto
tests/harness/executor/cases.go

Fix code generation for Go for repeated.items.enum.{in, not_in}
validations, and add test cases.
Fixes #377
Signed-off-by: zeromberto <ze.romberto@gmail.com>

Fix support for repeated embedded enums inclusion check in go

---

templates/cc/register.go
tests/harness/cases/oneofs.proto

The [camelCase implementation](https://github.com/lyft/protoc-gen-star/blob/d607749499f045f8b274bd2f5dd2d04ef4163434/lang/go/camel.go#L31) that PGS uses doesn't replace underscores before numbers, but the protobuf C++ code generator does. Fix and add a test case.
Fixes #372

Fix C++ oneof validation with _number in name

---

Makefile
go.mod
tests/go.mod

I believe this should work fine with go1.12 as well. So let's enable support for go modules for go 1.12 users too (like us :))
CI passed all tests

Reduce min go version to go1.12

---

bazel/pgv_proto_library.bzl
bazel/protobuf.bzl

Since the generated PGV code uses static registration, it needs to be compiled in a cc_library rule with alwayslink set to 1. Before this change, that library also included protobuf code, which means that all generated code for any message type was being included in any consuming binaries. This patch moves the generated .cc and .h files into a separate library that the linker can prune symbols from.

Create a separate cc_library for proto source

---

bazel/repositories.bzl

The version used before was not correctly providing ProtoInfo providers
for proto_library build rules. This was causing trouble with the latest
Bazel version. Fix the build by updating the protobuf version used.

Bump protobuf version to v3.14.0

---

.gitignore
java/pgv-java-validation/src/main/java/io/envoyproxy/pgv/validation/JavaHarness.java
tests/harness/executor/harness.go
tests/harness/executor/worker.go
validate/validator.py

There's a bug in the way test failures are added up. If any harness returns a skipped test result, test failures in other harnesses are also ignored. This has been showing up in the master build, see `message - ignored - valid` and `message - ignored - valid (invalid field)` cases. Since `cc` skipped these cases, failures in python and java were ignored. 
Have fixed python and java, and have changed the test worker to report problems to the out channel per-harness-per-test-case, instead of only per-test-case.

Fix JavaHarness and test executor's results summation

---

tests/harness/python/BUILD
tests/harness/python/harness.py
validate/BUILD

Instead of hackily adjusting the Python path during execution, create a
py_library rule for validator.py and list it as a dependency of the
python harness binary.

List validator.py as a dependency for py harness

---

bazel/protobuf.bzl

Without this, using PGV as an external dependency whose rules then acted
on another external dependency was broken. This patch adds additional
logic to generate the correct paths even in that case.

Fix relative paths for external repositories

---

Makefile
README.md
tests/harness/executor/BUILD
tests/harness/executor/executor.go
tests/harness/executor/executor_test.sh

Make it possible to test all functionality using `bazel test //tests/...` instead of having to use `bazel run` with a target name and arguments, and speed up test execution on multi-core machines by sharding first by validator language and then by splitting the test cases for each language among multiple parallel invocations of the test executor using standard Bazel sharding infrastructure.
As a side effect of running `bazel test //tests/...` in CI, we're now running some tests that were previously skipped, like `//tests/harness/cc:cc_diamond_test`.
See https://docs.bazel.build/versions/master/test-encyclopedia.html#test-sharding for details on Bazel sharding.

Improve bazel test experience

---

python/protoc_gen_validate/validator.py
tests/harness/cases/messages.proto
tests/harness/executor/cases.go

A trailing `-%}` will remove whitespace before the next non-whitespace character. This lead to indentation issue in the generated code:
```
Traceback (most recent call last):
File "/private/var/tmp/_bazel_jfish/952dee0bae9a937b66c9760a1a3bb297/sandbox/darwin-sandbox/26/execroot/com_envoyproxy_protoc_gen_validate/bazel-out/darwin-fastbuild/bin/tests/harness/executor/executor_python_test.runfiles/com_envoyproxy_protoc_gen_validate/tests/harness/python/harness.py", line 42, in <module>
valid = validate(test_msg)
File "/private/var/tmp/_bazel_jfish/952dee0bae9a937b66c9760a1a3bb297/sandbox/darwin-sandbox/26/execroot/com_envoyproxy_protoc_gen_validate/bazel-out/darwin-fastbuild/bin/tests/harness/executor/executor_python_test.runfiles/com_envoyproxy_protoc_gen_validate/python/protoc_gen_validate/ …
```

Fix indentation in python codegen for required oneof

---

java/pgv-java-stub/src/test/java/io/envoyproxy/pgv/StringValidationTest.java
java/pom.xml

The email validation is too restrictive. For example `some@email.africa` is considered as invalid.
This PR bumps commons-validator to the last version: [1.7](https://commons.apache.org/proper/commons-validator/changes-report.html#a1.7) (2020-08-07). The previous version (1.6) was rather old (2017-02-21).
Domain validation and thus email validation have been improved by this release.

Bump apache commons-validator:1.7

---

.circleci/config.yml
java/RELEASING.md

Support using CI to build and upload named versions after main has already changed.

Support releasing named Java versions

---

Makefile
README.md
module/validate.go
tests/harness/cases/other_package/embed.proto

Adds support for the `module=example.com/foo` flag [described here](https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation).
This flag "strips" of the provided prefix from the output path. In effect it makes it possible to output the generated files in any sub folder, but the import paths, module and packages "line up".
Fixes #342

Module parameter support

---

python/requirements.in
python/setup.cfg

[ipaddress](https://pypi.org/project/ipaddress/) from PyPi is an out of date backport of the [ipaddress module](https://docs.python.org/3/library/ipaddress.html) in the standard library that is designed to support Python versions < 3.3.
Since this project requires python 3.6, we should be able to use the stdlib and drop this package as a dependency.
This issue arose due vulnerability scanner indicating that [ipaddress](https://pypi.org/project/ipaddress/) from PyPi was 'high risk'.
Signed-off-by: Ryan Kelly <user@4kelly.com>

Python: drop ipaddress dependency, use std version instead

---

Dockerfile
python/setup.cfg

Bump version number to drop ipaddress dependency.
https://github.com/envoyproxy/protoc-gen-validate/pull/479

Bump python version number

---

templates/go/file.go
templates/goshared/map.go
templates/goshared/register.go

Sort the keys before iteration to make the iteration order
deterministic. This fixes a test flake where the first error returned by
ValidateAll() didn't match the error returned by Validate(). Since the
iteration order was unspecified, ValidateAll() would sometimes return
the same set of errors in different orders.

Make iteration order for Go maps consistent

---

bazel/repositories.bzl

So pgv_dependencies can be used as below in airtight environment
This is a backward compatible change
usage example:
```
load("@com_envoyproxy_protoc_gen_validate//bazel:repositories.bzl", "pgv_dependencies")
pgv_dependencies(maven_repos = ["https://my-corporation.com/repository/maven-all"])
```

supporting using  different maven repo

---

templates/goshared/map.go
tests/harness/cases/maps.proto
tests/harness/executor/cases.go

This allows defining local variables without them conflicting with other
local variables for the same parent message. This patch also adds a test
case to prevent regressions in the future.
Fixes #521

Perform Go map key sorting inside a scope

---

.gitignore
Makefile
java/pgv-java-validation/pom.xml
java/pgv-java-validation/src/main/java/io/envoyproxy/pgv/validation/BUILD
templates/go/file.go
templates/goshared/register.go
tests/harness/cases/BUILD
tests/harness/cases/enums.proto
tests/harness/cases/yet_another_package/BUILD
tests/harness/cases/yet_another_package/embed.proto
tests/harness/executor/BUILD
tests/harness/executor/cases.go
tests/harness/go/main/BUILD
tests/harness/go/main/harness.go

I am trying to fix https://github.com/envoyproxy/protoc-gen-validate/issues/511
Following the fix I noticed another bug in the go import statement generation for enums, go package names overlap. I tried to fix it but I am not sure to understand how harness works.
When executing the make task `testcases`, I am able to generate fixed pb files. Imports look like this:
```
_go "github.com/envoyproxy/protoc-gen-validate/tests/harness/cases/other_package/go"
_go1 "github.com/envoyproxy/protoc-gen-validate/tests/harness/cases/yet_another_package/go"
```
But when I am running `harness`, generated files are still broken, imports are not name correctly:
```
_go "github.com/envoyproxy/protoc-gen-validate/tests/harness/cases/other_package/go"
_go …
```

Fix enum import in repeated field

---

validate/validate.proto

It looks like `len_bytes` is like `len` which is an exact match, not a minimum match.

doc: correct comment describing string.len_bytes

---

README.md
java/pgv-java-grpc/pom.xml
java/pgv-java-stub/pom.xml
java/pgv-java-validation/pom.xml
java/pom.xml

Optional field support requires updating the protobuf and grpc java dependencies.
protobuf-maven-plugin -> 0.6.1
protobuf -> 3.19.1
protoc -> 3.19.1
grpc -> 1.42.1

Upgrade java protobuf, protoc, and grpc deps for 'optional' support

---

Makefile
templates/cc/register.go
templates/go/file.go
templates/goshared/register.go
tests/harness/cases/enums.proto
tests/harness/cases/other_package/embed.proto
tests/harness/cases/strings.proto
tools.go
validate/validate.h

1) Fix regression from
https://github.com/envoyproxy/protoc-gen-validate/pull/529. The
code needs to handle enums at file scope and in a message. At the
same time also handle arbitrary nesting.
2) Fix regression from https://github.com/envoyproxy/protoc-gen-validate/pull/537
when dealing with single element string oneofs (and possibly other
types being returned as pointer types vs. value types and breaking in
queries. This fixes that for both C++ and Go. It's possible this fix
shoudl be in PG* but doing it here for simplicity.
3) Modify the C++ validator registry to have polymorphic lookup
capability which I want to use in Envoy.
Signed-off-by: Matt Klein <mklein@lyft.com>

Various small fixes

---

templates/goshared/enum.go
tests/harness/cases/enums.proto

Need to use Value() to remove any pointer in the case of
an optionally present field.
Signed-off-by: Matt Klein <mklein@lyft.com>

enum: fix another regression inside of oneof

---

.circleci/config.yml
java/pgv-artifacts/pom.xml
java/pgv-java-stub/pom.xml
java/pom.xml

Update the build system to generate artifacts for MacOS on ARM64
to support Apple Silicon / M1 machines.

Java: Support for osx-aarch_64 architecture

---

.clang-format
templates/cc/message.go
tests/harness/cc/BUILD
tests/harness/cc/diamond_test.cc
tests/harness/cc/other.proto
tests/harness/cc/polymorphic_test.cc
validate/validate.h

The previous iteration does not make ASAN happy because of the implicit
static cast between Message and concrete type. This PR reverts that
change, adds a new abstract validation registry, and explicitly performs
a dynamic cast when asked to do so. It also checks to make sure a
validator exists for the passed in message.
Also add a .clang-format so at least manual formatting can be done.
Signed-off-by: Matt Klein <mklein@lyft.com>

C++: Fix polymorphic lookup and add tests

---

python/protoc_gen_validate/validator.py
tests/harness/cases/oneofs.proto
tests/harness/executor/cases.go

When ignore_empty used by a field inside a oneof then the generated python code was invalid. This is fixed by removal of the whitespace removal in the template to ensure if clause goes onto newline with base indentation.
Signed-off-by: James Fish <jfish@pinterest.com>

Fix indentation of python templates with ignore_empty fields inside oneof

---

.github/workflows/maven-publish.yaml

even though the regex `v[0-9]+.[0-9]+.[0-9]+(-rc.[0-9]+)*` is valid, github doesn't appear to be happy with it. Simplifying to `v*.*.*` is fine
Signed-off-by: Elliot Jackson <13633636+ElliotMJackson@users.noreply.github.com>

Simplify build trigger filter pattern

---

.github/workflows/maven-publish.yaml

Stupidly, I messed up the defined in the github action which caused it to fail on main. The solution itself is not ideal, I have raised #647 to fix this down the track
Signed-off-by: Elliot Jackson <13633636+ElliotMJackson@users.noreply.github.com>

bump version in ci

---

go.mod

Outlined in #655 
A number of versions were created inadvertently whilst attempting to resolve the maven relocation. This has negatively affected our golang community. 
Retracting based on modules [documentation](https://go.dev/ref/mod#go-mod-file-retract):
> consider a case where the author of module example.com/m publishes version v1.0.0 accidentally. To prevent users from upgrading to v1.0.0, the author can add two retract directives to go.mod, then tag v1.0.1 with the retractions.
> ```
> retract (
>     v1.0.0 // Published accidentally.
>     v1.0.1 // Contains retractions only.
> )
> ```
> When a user runs go get example.com/m@latest, the go command reads retractions from v1.0.1, which is now the highest version. Both v1.0.0 and v1.0.1 are retracted, so the go command will upgrade …

Retract accidentally published versions

---

README.md

envoy proxy is mentioned a few times in the readme, this PR updates them to bufbuild

Update readme groupID references

---

README.md

Remove misplaced `]` in the Readme maps min_pairs/max_pairs examples.

Readme map examples have a misplaced `]`

---

bazel/repositories.bzl

[zlib 1.2.13 release notes](https://github.com/madler/zlib/releases/tag/v1.2.13) Fix a bug when getting a gzip header extra field with inflateGetHeader(). This remedies [CVE-2022-37434](https://nvd.nist.gov/vuln/detail/CVE-2022-37434). Due to the bug fix, any installations of 1.2.12 or earlier should be replaced with 1.2.13.

Upgrade zlib to 1.2.13 to resolve CI failure

---

java/pgv-java-stub/src/main/java/io/envoyproxy/pgv/StringValidation.java

Replaces the existing UUID validation implementation with the UUID implementation that was added to Java in version 15. This implementation is significantly faster than our previous implementation, and requires fewer allocations (in fact only one global allocation, which is lazy and cached from there on out). Only SIMD vector instructions could be used to make it even faster.

Improve Java UUID Validation Performance

---

Dockerfile

TCN-611 Upgrade bazel to 5.3.1

---

.github/workflows/goreleaser.yaml
.goreleaser.yaml

1. Go Releaser is configured to `keep-existing` release comments so this will use the Github auto-generated release content. There is no need to expand on this
2. A series of configurable items are set to defaults, these have been removed from config. 
3. Some information was left over from my branch, this has been removed

TCN-464 fix goreleaser syntax

---

java/pgv-artifacts/pom.xml

Pointed out by the wonderful @donbeave
There is an execution for osx-aarch_64, but not execution for linux-aarch_64 in the `pom.xml` file
Building a Java application on Linux ARM fails... The error is:
```
Could not find protoc-gen-validate-0.6.13-linux-aarch_64.exe (io.envoyproxy.protoc-gen-validate:protoc-gen-validate:0.6.13).
```
resolves #680

GH-680 add linux aarch x64 support to pom

---

python/README.md
python/protoc_gen_validate/validator.py
python/requirements.in
python/setup.cfg
tests/harness/python/harness.py

This change implements the `validate_all` function through the [ast](https://docs.python.org/3/library/ast.html) module in the python standard library, which allows PGV to return all validate error messages at once.
```proto
//entities.proto
message Person {
uint64 id    = 1 [(validate.rules).uint64.gt    = 999];
string email = 2 [(validate.rules).string.email = true];
string name  = 3 [(validate.rules).string = {
pattern:   "^[^[0-9]A-Za-z]+( [^[0-9]A-Za-z]+)*$",
max_bytes: 256,
}];
Location home = 4 [(validate.rules).message.required = true];
message Location {
double lat = 1 [(validate.rules).double = { gte: -90,  lte: 90 }];
double lng = 2 [(validate.rules).double = { gte: -180, lte: 180 }];
}
}
```
```python
from entities_pb2 import Person
from protoc_gen_validate.validator import …
```

Python: Support for `validate_all` function

---

.dockerignore
README.md

Highlighted by our valued contributor @HaloWorld in #606, the `development` section of our readme needs some changes. This really does need a lot more work but should do the trick for now. 
resolves #690

Improve Development section of readme

---

.github/dependabot.yml

It is currently failing [1] as it tries to open more PRs than it is allowed to.
1: https://github.com/bufbuild/protoc-gen-validate/network/updates/495752775

Increase dependabot maximum PR limit for maven

---

.github/actions/github-tag-action/entrypoint.sh

Currently, a merge to main triggers a new `minor` tag. Until we build some confidence into the codebase, I think we should bump releases as a `SNAPSHOT` until verified. This will prevent accidental publishing of unstable releases.

Default version bump to prerelease

---

README.md

Highlighted by our wonderful community in #728, our readme was pointing our gomodule to `/bufbuild/` this is incorrect.

GH-728 Fix typo in readme

---

README.md

Close #764
You can download prebuilt binaries from GitHub Releases.

docs: fix installation

---

bazel/go/BUILD
bazel/pgv_proto_library.bzl

It wasn't using absolute labels, so the pgv_go_proto_library macro tries to reference non-existent labels in the users workspace.
Also define the go_proto_compiler rule once, rather than one per go_proto_library.

fix(bazel): make pgv compiler usable

---

python/pyproject.toml

The current pypi package fails snyk with ReDoS (Regex Expression Denial of Service) security issue.
[SNYK-PYTHON-WHEEL-3180413](https://security.snyk.io/vuln/SNYK-PYTHON-WHEEL-3180413)

Require wheel at least 0.38.1

---

README.md

Move v2 link around and add bold/italics

---

bazel/repositories.bzl

Currently, running gazelle fails:
```
$ bazel run //:gazelle  -- -help
ERROR: Traceback (most recent call last):
File "/home/alex/.cache/bazel/_bazel_alex/6ff60870017843370a59ce449c5a420a/external/bazel_gazelle/internal/BUILD.bazel", line 19, column 26, in <toplevel>
gazelle_binary_test_suite()
File "/home/alex/.cache/bazel/_bazel_alex/6ff60870017843370a59ce449c5a420a/external/bazel_gazelle/internal/gazelle_binary_test.bzl", line 27, column 19, in gazelle_binary_test_suite
unittest.suite(
File "/home/alex/.cache/bazel/_bazel_alex/6ff60870017843370a59ce449c5a420a/external/bazel_skylib/lib/unittest.bzl", line 269, column 18, in _suite
test_rule(name = test_name)
Error: 'struct' object is not callable
ERROR: /home/alex/code/protoc-gen-validate/BUILD.bazel:9:8: every rule of type …
```

Update skylib to fix gazelle

---

.github/dependabot.yml
.github/workflows/ci.yaml
.github/workflows/goreleaser.yaml
.github/workflows/python-package.yaml

Allows dependabot to handle github-actions and pip dependencies. 
It also includes the update of the available github-actions versions
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

Handle github-actions and pip dependencies

---

.goreleaser.yaml

This patch ensures cgo is disabled when building releases for PGV, making the binaries statically-linked for all targeted linux architectures.
Fixes #1051 
Verified locally with `goreleaser build`:
```sh
$ file protoc-gen-validate_linux_amd64_v1/protoc-gen-validate 
protoc-gen-validate: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=tb7sMSnjQh-7-8dwj-lH/T9787ev59A_KyorW6mad/v6PRV3ZwTB6tQWHc6xHc/T7TZq-XGFpsGNognhgR4, stripped
$ file protoc-gen-validate_linux_arm64/protoc-gen-validate
protoc-gen-validate: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=vCwX0aApdg5K4vpifCvn/5E2XJTfVojTMaqafL4ut/QlkXLuZKKxztZHPB5JGZ/Gd0NEotlWEWiD4KPwzjb, stripped
$ file protoc-gen-validate_linux_386/protoc-gen-validate …
```

Statically build all releases

---

README.md
python/README.md

The example regular expression introduced in https://github.com/bufbuild/protoc-gen-validate/commit/10eb9dbe665160f47abfeca829417b56e9b8c73c does not seem to work as intended, due to nesting a negated range inside another range:
```
❯ jshell --class-path ~/.m2/repository/com/google/re2j/re2j/1.7/re2j-1.7.jar
|  Welcome to JShell -- Version 17.0.9
|  For an introduction type: /help intro
jshell> com.google.re2j.Pattern p = com.google.re2j.Pattern.compile("^[^[0-9]A-Za-z]+( [^[0-9]A-Za-z]+)*$");
p ==> ^[^[0-9]A-Za-z]+( [^[0-9]A-Za-z]+)*$
jshell> p.matches(pattern, "Protocol Buffers");
$4 ==> false
jshell> p.matches(pattern, "Matt Brown");
$5 ==> false
```
The nesting of ranges in the example is also redundant - if you are going to specify that only `[A-Za-z]` is valid than including [^0-9]` …

Fix incorrect regex on Person.name field

---

.github/workflows/maven-deploy.yaml
.github/workflows/maven-release.yaml
.github/workflows/maven-verify.yaml
java/.mvn/wrapper/maven-wrapper.properties
java/mvnw
java/mvnw.cmd
java/pom.xml
java/settings.xml

Update the Maven release build to use the right secret names, switch to using the Maven wrapper for consistent builds, and clean up the settings.xml to remove unneeded sections.

Fix Maven release build

---

bazel/protobuf.bzl

This is now longer allowed in Bazel 8 and was flipped via `--incompatible_disallow_struct_provider_syntax`.
Once merged, please also backport to the v1.1.1-SNAPSHOTS.

Return a provider from a rule instead of a struct

---

bazel/pgv_proto_library.bzl
tests/harness/BUILD
tests/harness/cc/BUILD
validate/BUILD

Closes https://github.com/bufbuild/protoc-gen-validate/issues/1199
This is a more minimal change to simply migrate away from rules_cc's  cc_proto_library without updating all the external deps.
This will prepare for the upcoming 0.1.X release of rules_cc where cc_proto_library is removed.

Migrate to cc_proto_library from com_google_protobuf

---

java/pom.xml

Maven releases require a developers entry to publish to Maven central.

Add Maven developers entry
